apiVersion: v1
kind: Namespace
metadata:
  name: kollerdevhub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-demo
  namespace: kollerdevhub
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpbin-demo
  template:
    metadata:
      labels:
        app: httpbin-demo
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-demo
  namespace: kollerdevhub
spec:
  selector:
    app: httpbin-demo
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-demo
  namespace: kollerdevhub
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: httpbin.cluster-b.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpbin-demo
                port:
                  number: 80
